### ISSUE TITLE
How to use it on Laravel Santum + Nuxt Js

### ISSUE THREAD

**Issue by AEK-BKF** [renoki-co/echo-server#9]
Hello,
Thanks for this awesome package.
Please could you post an example how to use it with Laravel Api and Nuxt Js client.

Thanks

**Comment by rennokki** [comment]
I've been working on external usage, so the latest Echo Server release (3.0.1) fixes a lot of the authentication issues and client incompatibilities.

So:

1. [Check on how to implement this in JS (use the @soketi/soketi-js package to >=1.1.0)](https://github.com/renoki-co/echo-server#client-configuration)
2. Because Echo Server is a mix between Socket.IO and Pusher, you will need [a separate Echo client which is called Soketi.js](https://github.com/soketi/soketi-js), a hard fork of Laravel Echo.
3. In Soketi.js docs, you will see [authentication with Sanctum](https://github.com/soketi/soketi-js#authorizing-sanctum) section which is a brief copypasta of how [Laravel Echo does authentication under the hood using authorizers](https://laravel.com/docs/8.x/sanctum#authorizing-private-broadcast-channels)
